### ISSUE TITLE
Various errors

### ISSUE THREAD

**Issue by Jianhuax** [classycodeoss/mobile-scanning-demo#1]
In cloning the repo, npm install, and ng serve, an error in console saying Error: Uncaught (in promise): Error: Service workers are disabled or not supported by this browser. When in ng build --prod, this error in console is gone. So far so good.

However, when a scan was completed in dev mode, the browser froze. The console error states error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: '[object Map Iterator]'. Current value: '[object Map Iterator]'.

When a scan was completed in prod mode, the console error states Uncaught (in promise) DOMException: Failed to load because no supported source was found.

Then when linking to https://ean-crab-scanner.web.app/, and completed a scan, no error were logged in console.

Thoughts?

**Comment by suzukieng** [comment]
Hi @Jianhuax , I just updated the project to use Angular 13 and also fixed the error you observed.
